---
abstract: 'display a graphical summary of a BLAST report'
author:
  - 'Shuai Weng <shuai@genome.stanford.edu>'
  - 'John Slenk <jces@genome.stanford.edu>'
  - 'Robert Buels <rmb32@cornell.edu>'
build_requires:
  Capture::Tiny: 0
  File::Spec::Functions: 0
  File::Temp: 0
  IO::String: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200003, CPAN::Meta::Converter version 2.110390'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-GMOD-Blast-Graph
requires:
  Bio::Root::IO: 0
  Bio::SearchIO: 0
  CGI: 0
  Carp: 0
  Exporter: 0
  File::Spec: 0
  GD: 0
  integer: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Bio-GMOD-Blast-Graph
  homepage: http://search.cpan.org/dist/Bio-GMOD-Blast-Graph
  repository: http://github.com/gmod/Bio-GMOD-Blast-Graph
version: 0.02
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/@Basic/GatherDir'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/@Basic/PruneCruft'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/@Basic/ManifestSkip'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/@Basic/MetaYAML'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/@Basic/Readme'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/@Basic/ExtraTests'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/@Basic/ExecDir'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/@Basic/ShareDir'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/@Basic/MakeMaker'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/@Basic/Manifest'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/@Basic/TestRelease'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/@Basic/ConfirmRelease'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/@Basic/UploadToCPAN'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@Filter/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@Filter/MetaResources'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Filter/Authority'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Filter/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Filter/AutoPrereqs'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.200003
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.200003
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.200003
x_authority: cpan:RBUELS
